// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIV7DTGbGPyKDXsUNCTEYxywLcspi65c',
    appId: '1:882169408481:web:dcdc13385dd1c6820400a0',
    messagingSenderId: '882169408481',
    projectId: 'fundamentos-movil',
    authDomain: 'fundamentos-movil.firebaseapp.com',
    storageBucket: 'fundamentos-movil.appspot.com',
    measurementId: 'G-ZRG54B9757',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qbmusnEM3bmrfI6m2MrHv17OlouI5Xo',
    appId: '1:882169408481:android:5dc6d0206f020c100400a0',
    messagingSenderId: '882169408481',
    projectId: 'fundamentos-movil',
    storageBucket: 'fundamentos-movil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIwoqnIGJqhY0SqBolA_P46kF6Zquho8',
    appId: '1:882169408481:ios:eeee21d461b044b80400a0',
    messagingSenderId: '882169408481',
    projectId: 'fundamentos-movil',
    storageBucket: 'fundamentos-movil.appspot.com',
    iosClientId: '882169408481-7itdk2qp1lc13irqmd8ccmtgaj7fkc21.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendedores',
  );
}
